#!/usr/bin/env python3
"""Apply approved transformation proposals to the database.

This script reads a proposals JSON file (generated by transform_citations.py),
filters for approved proposals, and applies them to the RootsMagic database.

Safety features:
- Only applies proposals with status='approved' or status='modified'
- Creates backup before applying changes
- Dry-run mode by default
- Detailed logging

Usage:
    uv run python scripts/citation_compliance/apply_proposals.py proposals.json --dry-run
    uv run python scripts/citation_compliance/apply_proposals.py proposals.json --apply
"""

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from src.rmcitecraft.database.connection import connect_rmtree


def extract_field_from_blob(fields_text: str, field_name: str) -> str:
    """Extract a field value from the SourceTable.Fields XML text."""
    if not fields_text:
        return ""
    pattern = rf'<Name>{field_name}</Name>\s*<Value>(.*?)</Value>'
    match = re.search(pattern, fields_text, re.DOTALL)
    return match.group(1) if match else ""


def update_field_in_blob(fields_text: str, field_name: str, new_value: str) -> str:
    """Update a field value in the SourceTable.Fields XML text."""
    pattern = rf'(<Name>{field_name}</Name>\s*<Value>)(.*?)(</Value>)'

    def replacer(match):
        return match.group(1) + new_value + match.group(3)

    return re.sub(pattern, replacer, fields_text, flags=re.DOTALL)


def load_proposals(filepath: str) -> dict:
    """Load proposals from JSON file."""
    with open(filepath, 'r') as f:
        return json.load(f)


def filter_approved_proposals(proposals_data: dict) -> list[dict]:
    """Filter proposals to only approved or modified ones."""
    approved = []
    for proposal in proposals_data.get('proposals', []):
        if proposal.get('status') in ('approved', 'modified'):
            approved.append(proposal)
    return approved


def create_backup(cursor, proposals: list[dict]) -> dict:
    """Create backup of sources before modification."""
    source_ids = [p['source_id'] for p in proposals]

    backup = {
        'timestamp': datetime.now().isoformat(),
        'description': 'Pre-transformation backup of approved proposals',
        'source_count': len(source_ids),
        'records': []
    }

    for source_id in source_ids:
        cursor.execute(
            "SELECT SourceID, Name, CAST(Fields AS TEXT) FROM SourceTable WHERE SourceID = ?",
            (source_id,)
        )
        row = cursor.fetchone()
        if row:
            backup['records'].append({
                'source_id': row[0],
                'name': row[1],
                'original_fields': row[2]
            })

    return backup


def apply_proposals(cursor, proposals: list[dict]) -> dict[str, Any]:
    """Apply approved proposals to the database.

    Returns:
        Statistics about applied changes
    """
    stats = {
        'total': len(proposals),
        'applied': 0,
        'skipped': 0,
        'errors': 0,
        'details': []
    }

    for proposal in proposals:
        source_id = proposal['source_id']
        proposed = proposal.get('proposed', {})

        # Get current fields
        cursor.execute(
            "SELECT CAST(Fields AS TEXT) FROM SourceTable WHERE SourceID = ?",
            (source_id,)
        )
        row = cursor.fetchone()

        if not row:
            stats['skipped'] += 1
            stats['details'].append({
                'source_id': source_id,
                'status': 'skipped',
                'reason': 'Source not found'
            })
            continue

        fields_text = row[0]
        modified = False

        # Apply short footnote if proposed
        new_sf = proposed.get('short_footnote')
        if new_sf:
            # Encode HTML entities for XML storage
            new_sf_encoded = new_sf.replace('<', '&lt;').replace('>', '&gt;')
            fields_text = update_field_in_blob(fields_text, 'ShortFootnote', new_sf_encoded)
            modified = True

        # Apply bibliography if proposed
        new_bib = proposed.get('bibliography')
        if new_bib:
            # Encode HTML entities for XML storage
            new_bib_encoded = new_bib.replace('<', '&lt;').replace('>', '&gt;')
            fields_text = update_field_in_blob(fields_text, 'Bibliography', new_bib_encoded)
            modified = True

        if modified:
            try:
                cursor.execute(
                    "UPDATE SourceTable SET Fields = ? WHERE SourceID = ?",
                    (fields_text.encode('utf-8'), source_id)
                )
                stats['applied'] += 1
                stats['details'].append({
                    'source_id': source_id,
                    'status': 'applied',
                    'changes': {
                        'short_footnote': bool(new_sf),
                        'bibliography': bool(new_bib)
                    }
                })
            except Exception as e:
                stats['errors'] += 1
                stats['details'].append({
                    'source_id': source_id,
                    'status': 'error',
                    'error': str(e)
                })
        else:
            stats['skipped'] += 1
            stats['details'].append({
                'source_id': source_id,
                'status': 'skipped',
                'reason': 'No changes to apply'
            })

    return stats


def main():
    parser = argparse.ArgumentParser(
        description='Apply approved transformation proposals to the database.'
    )
    parser.add_argument(
        'proposals_file',
        help='Path to proposals JSON file'
    )
    parser.add_argument(
        '--db',
        default='data/Iiams.rmtree',
        help='Path to RootsMagic database'
    )
    parser.add_argument(
        '--apply',
        action='store_true',
        help='Apply changes (default is dry-run)'
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Preview mode without changes (default)'
    )
    parser.add_argument(
        '--backup-dir',
        default='backup',
        help='Directory for backup files'
    )
    parser.add_argument(
        '--auto-approve-confidence',
        type=float,
        help='Auto-approve pending proposals with confidence >= threshold'
    )

    args = parser.parse_args()

    is_dry_run = not args.apply

    print("=" * 70)
    print("  APPLY TRANSFORMATION PROPOSALS")
    print("=" * 70)
    print()
    print(f"Proposals file: {args.proposals_file}")
    print(f"Mode: {'DRY-RUN (no changes)' if is_dry_run else 'APPLY CHANGES'}")
    print()

    # Load proposals
    proposals_data = load_proposals(args.proposals_file)

    # Auto-approve if threshold specified
    if args.auto_approve_confidence is not None:
        for proposal in proposals_data.get('proposals', []):
            if proposal.get('status') == 'pending':
                conf = proposal.get('confidence', {})
                min_conf = min(
                    conf.get('short_footnote', 1.0) if proposal.get('proposed', {}).get('short_footnote') else 1.0,
                    conf.get('bibliography', 1.0) if proposal.get('proposed', {}).get('bibliography') else 1.0
                )
                if min_conf >= args.auto_approve_confidence:
                    proposal['status'] = 'approved'
                    proposal['review_notes'] = f'Auto-approved: confidence {min_conf:.2f} >= {args.auto_approve_confidence}'

    # Filter to approved proposals
    approved = filter_approved_proposals(proposals_data)

    print(f"Total proposals in file: {len(proposals_data.get('proposals', []))}")
    print(f"Approved/modified proposals: {len(approved)}")
    print()

    if not approved:
        print("No approved proposals to apply.")
        print()
        print("To approve proposals:")
        print("  1. Edit the proposals JSON file")
        print("  2. Change 'status' from 'pending' to 'approved'")
        print("  3. Or use --auto-approve-confidence THRESHOLD")
        return

    # Show summary of approved proposals
    print("Approved proposals by source type:")
    by_type: dict[str, int] = {}
    for p in approved:
        st = p.get('source_type', 'Unknown')
        by_type[st] = by_type.get(st, 0) + 1

    for st, count in sorted(by_type.items(), key=lambda x: -x[1]):
        print(f"  {st:25} {count}")
    print()

    if is_dry_run:
        print("=" * 70)
        print("  DRY-RUN MODE - No changes will be made")
        print("=" * 70)
        print()

        # Show what would be changed
        for proposal in approved[:10]:
            print(f"Would update SourceID {proposal['source_id']}: {proposal['source_name'][:50]}")
            proposed = proposal.get('proposed', {})
            if proposed.get('short_footnote'):
                print(f"  - Update ShortFootnote")
            if proposed.get('bibliography'):
                print(f"  - Update Bibliography")

        if len(approved) > 10:
            print(f"... and {len(approved) - 10} more")

        print()
        print("Run with --apply to make these changes.")
        return

    # Connect to database
    conn = connect_rmtree(args.db, read_only=False)
    cursor = conn.cursor()

    # Create backup
    print("Creating backup...")
    backup = create_backup(cursor, approved)

    backup_dir = Path(args.backup_dir)
    backup_dir.mkdir(exist_ok=True)
    backup_file = backup_dir / f"proposals_backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"

    with open(backup_file, 'w') as f:
        json.dump(backup, f, indent=2)
    print(f"Backup saved to: {backup_file}")
    print()

    # Apply proposals
    print("Applying proposals...")
    stats = apply_proposals(cursor, approved)

    # Commit changes
    conn.commit()
    conn.close()

    # Display results
    print()
    print("=" * 70)
    print("  RESULTS")
    print("=" * 70)
    print()
    print(f"Total proposals:  {stats['total']}")
    print(f"Applied:          {stats['applied']}")
    print(f"Skipped:          {stats['skipped']}")
    print(f"Errors:           {stats['errors']}")
    print()

    if stats['errors'] > 0:
        print("Errors:")
        for detail in stats['details']:
            if detail.get('status') == 'error':
                print(f"  SourceID {detail['source_id']}: {detail['error']}")
        print()

    # Save results log
    results_file = backup_dir / f"proposals_results_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(results_file, 'w') as f:
        json.dump({
            'timestamp': datetime.now().isoformat(),
            'proposals_file': args.proposals_file,
            'stats': stats
        }, f, indent=2)
    print(f"Results saved to: {results_file}")
    print()

    print("=" * 70)
    print("  COMPLETE")
    print("=" * 70)


if __name__ == '__main__':
    main()
